### ISSUE TITLE
[Bug]: Missing uppercase in `pip install --upgrade pip` error message

### ISSUE THREAD

**Issue by Benjamin-Loison** [Benjamin-Loison/termux-packages#3]
### Problem description

```bash
pip
```
```
The program pip is not installed. Install it by executing:
 pkg install python-pip
```

```bash
pip install --upgrade pip
```
```
ERROR: Installing pip is forbidden. this will break the python-pip package (termux).
```

Related to [Benjamin-Loison/waydroid/issues/1](https://github.com/Benjamin-Loison/waydroid/issues/1).

### What steps will reproduce the bug?

Not read.

### System information

termux-info:

```

```

**Comment by Bhullarpreet22ji** [comment]
Did You Solved ??

**Comment by Benjamin-Loison** [comment]
It now returns:

```
ERROR: Installing pip is forbidden, this will break the python-pip package (termux).
```

**Comment by Benjamin-Loison** [comment]
@Bhullarpreet22ji

What is your precise issue? You need a more recent version of pip than what `python-pip` `pkg` package brings you?
